// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRwRC0hZ_1BlJoOn1RLsPUwf5tq6n7ji0',
    appId: '1:364540574109:web:d5be699464cf61c38d5774',
    messagingSenderId: '364540574109',
    projectId: 'nkap-46d6b',
    authDomain: 'nkap-46d6b.firebaseapp.com',
    storageBucket: 'nkap-46d6b.firebasestorage.app',
    measurementId: 'G-9MSN1GSVHQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvcctY6s0EuWlQYRTZl_n_LiixE5Enk4',
    appId: '1:364540574109:ios:bea79487d5a2e1b78d5774',
    messagingSenderId: '364540574109',
    projectId: 'nkap-46d6b',
    storageBucket: 'nkap-46d6b.firebasestorage.app',
    iosBundleId: 'com.njangitrust.njangiTrust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRwRC0hZ_1BlJoOn1RLsPUwf5tq6n7ji0',
    appId: '1:364540574109:web:6601675a509840918d5774',
    messagingSenderId: '364540574109',
    projectId: 'nkap-46d6b',
    authDomain: 'nkap-46d6b.firebaseapp.com',
    storageBucket: 'nkap-46d6b.firebasestorage.app',
    measurementId: 'G-1XFRGZ257W',
  );
}
